[
   Property_Set                                                         -- KW["property"] KW["set"] _1 KW["is"] _2 _3 KW["end"] _4 KW[";"],
   Property_Set.2:iter-star                                             -- _1,
   Property_Set.3:iter-star                                             -- _1,
   Property_Set                                                         -- KW["property"] KW["set"] _1 KW["is"] _2 _3 KW["end"] _4 KW[";"],
   Property_Set.2:iter-star                                             -- _1,
   Property_Set.3:iter-star                                             -- _1,
   Property_Set                                                         -- KW["property"] KW["set"] _1 KW["is"] _2 _3 KW["end"] _4 KW[";"],
   Property_Set.2:iter-star                                             -- _1,
   Property_Set.3:iter-star                                             -- _1,
   Constants                                                            -- KW["constant"],
   BasicPropertyAssociation                                             -- _1 KW["=>"] _2 _3 KW[";"],
   BasicPropertyAssociation.2:opt                                       -- _1,
   BasicPropertyAssociation                                             -- _1 KW["+=>"] _2 _3 KW[";"],
   BasicPropertyAssociation.2:opt                                       -- _1,
   PropertyAssociation                                                  -- _1 KW["=>"] _2 _3 _4 KW[";"],
   PropertyAssociation.2:opt                                            -- _1,
   PropertyAssociation                                                  -- _1 KW["+=>"] _2 _3 _4 KW[";"],
   PropertyAssociation.2:opt                                            -- _1,
   ContainedPropertyAssociation                                         -- _1 KW["=>"] _2 KW["applies"] KW["to"] _3 _4 KW[";"],
   ContainedPropertyAssociation.2:opt                                   -- _1,
   ContainedPropertyAssociation.3:iter-sep                              -- _1 KW[","],
   UniquePropertyIdentifier                                             -- _1 _2,
   UniquePropertyIdentifier.1:opt                                       -- _1,
   UniquePropertyIdentifier.1:opt.1:seq                                 -- _1 KW["::"],
   ContainedModelElementPath                                            -- _1 _2,
   ContainedModelElementPath.1:iter-sep                                 -- _1 KW["."],
   ContainedModelElementPath                                            -- _1,
   AnnexPath                                                            -- KW["annex"] _1 KW["{**"] _2 KW["**}"],
   StrCon                                                               -- KW["defined by annex"],
   ModalPropertyValue                                                   -- V  [V vs=2 [KW["("] _1] KW[")"]],
   ModalPropertyValue.1:iter-star                                       -- _1,
   ModalPropertyValue.1:iter-star.1:seq                                 -- _1 _2 KW[","],
   PropertyListValue                                                    -- KW["("] _1 KW[")"],
   PropertyListValue.1:iter-sep                                         -- _1 KW[","],
   PropertyListValue                                                    -- KW["("] _1 KW[")"],
   PropertyListValue.1:iter-sep                                         -- _1 KW[","],
   InBinding                                                            -- KW["in"] KW["binding"] KW["("] _1 KW[")"],
   InBinding.1:iter-sep                                                 -- _1 KW[","],
   FeatureGroupContainedPropertyAssociations                            -- _1,
   FeatureGroupContainedPropertyAssociations.1:iter                     -- _1,
   FeatureGroupType                                                     -- KW["feature"] KW["group"] _1 _2 _3 _4 _5 _6 KW["end"] _7,
   FeatureGroupType.2:opt                                               -- _1,
   FeatureGroupType.2:opt.1:seq                                         -- KW["prototypes"] _1,
   FeatureGroupType.3:opt                                               -- _1,
   FeatureGroupType.3:opt.1:seq                                         -- KW["features"] _1,
   FeatureGroupType.4:opt                                               -- _1,
   FeatureGroupType.4:opt.1:seq                                         -- KW["inverse"] KW["of"] _1,
   FeatureGroupType.5:opt                                               -- _1,
   FeatureGroupType.5:opt.1:seq                                         -- KW["properties"] _1,
   FeatureGroupType.6:iter-star                                         -- _1,
   FeatureGroupType                                                     -- KW["feature"] KW["group"] _1 _2 _3 _4 _5 _6 KW["end"] _7,
   FeatureGroupType.2:opt                                               -- _1,
   FeatureGroupType.2:opt.1:seq                                         -- KW["prototypes"] _1,
   FeatureGroupType.3:opt                                               -- _1,
   FeatureGroupType.3:opt.1:seq                                         -- KW["features"] _1,
   FeatureGroupType.4:opt                                               -- _1,
   FeatureGroupType.4:opt.1:seq                                         -- KW["inverse"] KW["of"] _1,
   FeatureGroupType.5:opt                                               -- _1,
   FeatureGroupType.5:opt.1:seq                                         -- KW["properties"] _1,
   FeatureGroupType.6:iter-star                                         -- _1,
   FeatureGroupType                                                     -- KW["feature"] KW["group"] _1 _2 _3 _4 _5 _6 KW["end"] _7,
   FeatureGroupType.2:opt                                               -- _1,
   FeatureGroupType.2:opt.1:seq                                         -- KW["prototypes"] _1,
   FeatureGroupType.3:opt                                               -- _1,
   FeatureGroupType.3:opt.1:seq                                         -- KW["features"] _1,
   FeatureGroupType.4:opt                                               -- _1,
   FeatureGroupType.4:opt.1:seq                                         -- KW["inverse"] KW["of"] _1,
   FeatureGroupType.5:opt                                               -- _1,
   FeatureGroupType.5:opt.1:seq                                         -- KW["properties"] _1,
   FeatureGroupType.6:iter-star                                         -- _1,
   FeatureGroupType                                                     -- KW["feature"] KW["group"] _1 _2 _3 _4 _5 _6 KW["end"] _7,
   FeatureGroupType.2:opt                                               -- _1,
   FeatureGroupType.2:opt.1:seq                                         -- KW["prototypes"] _1,
   FeatureGroupType.3:opt                                               -- _1,
   FeatureGroupType.3:opt.1:seq                                         -- KW["features"] _1,
   FeatureGroupType.4:opt                                               -- _1,
   FeatureGroupType.4:opt.1:seq                                         -- KW["inverse"] KW["of"] _1,
   FeatureGroupType.5:opt                                               -- _1,
   FeatureGroupType.5:opt.1:seq                                         -- KW["properties"] _1,
   FeatureGroupType.6:iter-star                                         -- _1,
   Prototypess                                                          -- _1,
   Prototypess.1:iter                                                   -- _1,
   Prototypess                                                          -- _1,
   Prototypess.1:iter                                                   -- _1,
   Prototypess                                                          -- _1,
   Featuress                                                            -- _1,
   Featuress.1:iter                                                     -- _1,
   Featuress                                                            -- _1,
   Featuress.1:iter                                                     -- _1,
   FeatureGroupTypeExtension                                            -- KW["feature"] KW["group"] _1 KW["extends"] _2 _3 _4 _5 _6 _7 _8 KW["end"] _9,
   FeatureGroupTypeExtension.3:opt                                      -- _1,
   FeatureGroupTypeExtension.4:opt                                      -- _1,
   FeatureGroupTypeExtension.4:opt.1:seq                                -- KW["prototypes"] _1,
   FeatureGroupTypeExtension.5:opt                                      -- _1,
   FeatureGroupTypeExtension.5:opt.1:seq                                -- KW["features"] _1,
   FeatureGroupTypeExtension.6:opt                                      -- _1,
   FeatureGroupTypeExtension.6:opt.1:seq                                -- KW["inverse"] KW["of"] _1,
   FeatureGroupTypeExtension.7:opt                                      -- _1,
   FeatureGroupTypeExtension.7:opt.1:seq                                -- KW["properties"] _1,
   FeatureGroupTypeExtension.8:iter-star                                -- _1,
   FeatureGroupTypeExtension                                            -- KW["feature"] KW["group"] _1 KW["extends"] _2 _3 _4 _5 _6 _7 _8 KW["end"] _9,
   FeatureGroupTypeExtension.3:opt                                      -- _1,
   FeatureGroupTypeExtension.4:opt                                      -- _1,
   FeatureGroupTypeExtension.4:opt.1:seq                                -- KW["prototypes"] _1,
   FeatureGroupTypeExtension.5:opt                                      -- _1,
   FeatureGroupTypeExtension.5:opt.1:seq                                -- KW["features"] _1,
   FeatureGroupTypeExtension.6:opt                                      -- _1,
   FeatureGroupTypeExtension.6:opt.1:seq                                -- KW["inverse"] KW["of"] _1,
   FeatureGroupTypeExtension.7:opt                                      -- _1,
   FeatureGroupTypeExtension.7:opt.1:seq                                -- KW["properties"] _1,
   FeatureGroupTypeExtension.8:iter-star                                -- _1,
   Inout                                                                -- KW["in"],
   Inout                                                                -- KW["out"],
   UniqueFeatureGroupTypeReferences                                     -- KW["inverse"] KW["of"] _1,
   PrototypeIdentifiers                                                 -- KW["inverse"] KW["of"] _1,
   PrototypeIdentifiers                                                 -- _1,
   UniqueFeatureGroupTypeReferences                                     -- _1,
   InFeatureGroupSpecU                                                  -- _1 KW[":"] _2 KW["feature"] KW["group"] _3,
   InFeatureGroupSpecU.2:opt                                            -- _1,
   InFeatureGroupSpecU.3:opt                                            -- _1,
   InFeatureGroupSpecP                                                  -- _1 KW[":"] _2 KW["feature"] KW["group"] _3,
   InFeatureGroupSpecP.2:opt                                            -- _1,
   InFeatureGroupSpecP.3:opt                                            -- _1,
   InFeatureGroupRefinementU                                            -- _1 KW[":"] KW["refined"] KW["to"] _2 KW["feature"] KW["group"] _3,
   InFeatureGroupRefinementU.2:opt                                      -- _1,
   InFeatureGroupRefinementU.3:opt                                      -- _1,
   InFeatureGroupRefinementP                                            -- _1 KW[":"] KW["refined"] KW["to"] _2 KW["feature"] KW["group"] _3,
   InFeatureGroupRefinementP.2:opt                                      -- _1,
   InFeatureGroupRefinementP.3:opt                                      -- _1,
   UniqueFeatureGroupTypeReference                                      -- _1 _2,
   UniqueFeatureGroupTypeReference.1:seq                                -- _1 KW["::"],
   None                                                                 -- KW["none"] KW[";"],
   EndToEndFlowSpec                                                     -- _1 KW[":"] KW["end"] KW["to"] KW["end"] KW["flow"] _2 _3 _4 _5 KW[";"],
   EndToEndFlowSpec.3:iter                                              -- _1,
   EndToEndFlowSpec.3:iter.1:seq                                        -- KW["->"] _1 KW["->"] _2,
   EndToEndFlowSpec.4:opt                                               -- _1,
   EndToEndFlowSpec.5:opt                                               -- _1,
   EndToEndFlowSpecRefinement                                           -- _1 KW[":"] KW["refined"] KW["to"] KW["end"] KW["to"] KW["end"] KW["flow"] _2 _3 KW[";"],
   EndToEndFlowSpecRefinement.2:opt                                     -- _1,
   EndToEndFlowSpecRefinement.3:opt                                     -- _1,
   EndToEndFlowSpecRefinement                                           -- _1 KW[":"] KW["refined"] KW["to"] KW["end"] KW["to"] KW["end"] KW["flow"] _2 KW[";"],
   FlowImplementation                                                   -- _1 _2 _3 KW[";"],
   FlowImplementation.2:opt                                             -- _1,
   FlowImplementation.3:opt                                             -- _1,
   FlowImplementation                                                   -- _1 _2 _3 KW[";"],
   FlowImplementation.2:opt                                             -- _1,
   FlowImplementation.3:opt                                             -- _1,
   FlowImplementation                                                   -- _1 _2 _3 KW[";"],
   FlowImplementation.2:opt                                             -- _1,
   FlowImplementation.3:opt                                             -- _1,
   FlowSourceImplementation                                             -- _1 KW[":"] KW["flow"] KW["source"] _2 _3,
   FlowSourceImplementation.2:iter-star                                 -- _1,
   FlowSourceImplementation.2:iter-star.1:seq                           -- _1 KW["->"] _2 KW["->"],
   FlowSinkImplementation                                               -- _1 KW[":"] KW["flow"] KW["sink"] _2 _3,
   FlowSinkImplementation.3:iter-star                                   -- _1,
   FlowSinkImplementation.3:iter-star.1:seq                             -- _1 KW["->"] _2 KW["->"],
   FlowPathImplementation                                               -- _1 KW[":"] KW["flow"] KW["path"] _2 _3 KW["->"] _4 _5,
   FlowPathImplementation.3:iter                                        -- _1,
   FlowPathImplementation.3:iter.1:seq                                  -- _1 KW["->"] _2 KW["->"],
   SubcomponentFlowIdentifier                                           -- _1 _2,
   SubcomponentFlowIdentifier.2:opt                                     -- _1,
   SubcomponentFlowIdentifier.2:opt.1:seq                               -- KW["."] _1,
   Prototype_Medium                                                     -- _1,
   Prototype_Medium.1:iter                                              -- _1,
   Subcomponent_Medium                                                  -- _1,
   Subcomponent_Medium.1:iter                                           -- _1,
   SubprogramCallSequence_Medium                                        -- _1,
   SubprogramCallSequence_Medium.1:iter                                 -- _1,
   Connection_Medium                                                    -- _1,
   Connection_Medium.1:iter                                             -- _1,
   Flows_Medium                                                         -- _1,
   Flows_Medium.1:iter                                                  -- _1,
   Flows_Medium                                                         -- _1,
   Flows_Medium.1:iter                                                  -- _1,
   Properties_Medium                                                    -- _1,
   Properties_Medium.1:iter                                             -- _1,
   Properties_Medium                                                    -- _1,
   Properties_Medium.1:iter                                             -- _1,
   Component_Implementation                                             -- _1 KW["implememtation"] _2 _3 _4 _5 _6 _7 _8 _9 _10 _11 KW["end"] _12 KW[";"],
   Component_Implementation.3:opt                                       -- _1,
   Component_Implementation.4:opt                                       -- _1,
   Component_Implementation.4:opt.1:seq                                 -- KW["prototypes"] _1,
   Component_Implementation.5:opt                                       -- _1,
   Component_Implementation.5:opt.1:seq                                 -- KW["subcomponent"] _1,
   Component_Implementation.6:opt                                       -- _1,
   Component_Implementation.6:opt.1:seq                                 -- KW["call"] _1,
   Component_Implementation.7:opt                                       -- _1,
   Component_Implementation.7:opt.1:seq                                 -- KW["connections"] _1,
   Component_Implementation.8:opt                                       -- _1,
   Component_Implementation.8:opt.1:seq                                 -- KW["flows"] _1,
   Component_Implementation.9:opt                                       -- _1,
   Component_Implementation.10:opt                                      -- _1,
   Component_Implementation.10:opt.1:seq                                -- KW["properties"] _1,
   Component_Implementation.11:opt                                      -- _1,
   Component_Implementation.11:opt.1:iter-star                          -- _1,
   Component_Implementation_Exension                                    -- _1 KW["implememtation"] _2 KW["extends"] _3 _4 _5 _6 _7 _8 _9 _10 _11 _12 KW["end"] _13 KW[";"],
   Component_Implementation_Exension.4:opt                              -- _1,
   Component_Implementation_Exension.5:opt                              -- _1,
   Component_Implementation_Exension.5:opt.1:seq                        -- KW["prototypes"] _1,
   Component_Implementation_Exension.6:opt                              -- _1,
   Component_Implementation_Exension.6:opt.1:seq                        -- KW["subcomponent"] _1,
   Component_Implementation_Exension.7:opt                              -- _1,
   Component_Implementation_Exension.7:opt.1:seq                        -- KW["call"] _1,
   Component_Implementation_Exension.8:opt                              -- _1,
   Component_Implementation_Exension.8:opt.1:seq                        -- KW["connections"] _1,
   Component_Implementation_Exension.9:opt                              -- _1,
   Component_Implementation_Exension.9:opt.1:seq                        -- KW["flows"] _1,
   Component_Implementation_Exension.10:opt                             -- _1,
   Component_Implementation_Exension.11:opt                             -- _1,
   Component_Implementation_Exension.11:opt.1:seq                       -- KW["properties"] _1,
   Component_Implementation_Exension.12:opt                             -- _1,
   Component_Implementation_Exension.12:opt.1:iter-star                 -- _1,
   ComponentImplementationName                                          -- _1 KW["."] _2,
   UniqueComponentImplementationReference                               -- _1 _2,
   UniqueComponentImplementationReference.1:opt                         -- _1,
   UniqueComponentImplementationReference.1:opt.1:seq                   -- _1 KW["::"],
   Component_Type_Extension                                             -- _1 _2 KW["extends"] _3 _4 _5 _6 _7 _8 _9 _10 KW["end"] _11,
   Component_Type_Extension.4:opt                                       -- _1,
   Component_Type_Extension.5:opt                                       -- _1,
   Component_Type_Extension.5:opt.1:seq                                 -- KW["prototypes"] _1,
   Component_Type_Extension.6:opt                                       -- _1,
   Component_Type_Extension.6:opt.1:seq                                 -- KW["features"] _1,
   Component_Type_Extension.7:opt                                       -- _1,
   Component_Type_Extension.7:opt.1:seq                                 -- KW["flows"] _1,
   Component_Type_Extension.9:opt                                       -- _1,
   Component_Type_Extension.9:opt.1:seq                                 -- KW["properties"] _1,
   Component_Type_Extension.10:opt                                      -- _1,
   Component_Type_Extension.10:opt.1:iter-star                          -- _1,
   Component_Type_Extension                                             -- _1 _2 KW["extends"] _3 _4 _5 _6 _7 _8 _9 _10 KW["end"] _11 KW[";"],
   Component_Type_Extension.4:opt                                       -- _1,
   Component_Type_Extension.5:opt                                       -- _1,
   Component_Type_Extension.5:opt.1:seq                                 -- KW["prototypes"] _1,
   Component_Type_Extension.6:opt                                       -- _1,
   Component_Type_Extension.6:opt.1:seq                                 -- KW["features"] _1,
   Component_Type_Extension.7:opt                                       -- _1,
   Component_Type_Extension.7:opt.1:seq                                 -- KW["flows"] _1,
   Component_Type_Extension.8:opt                                       -- _1,
   Component_Type_Extension.9:opt                                       -- _1,
   Component_Type_Extension.9:opt.1:seq                                 -- KW["properties"] _1,
   Component_Type_Extension.10:opt                                      -- _1,
   Component_Type_Extension.10:opt.1:iter-star                          -- _1,
   Component_Type_Extension                                             -- _1 _2 KW["extends"] _3 _4 _5 _6 _7 _8 _9 _10 KW["end"] _11 KW[";"],
   Component_Type_Extension.4:opt                                       -- _1,
   Component_Type_Extension.5:opt                                       -- _1,
   Component_Type_Extension.5:opt.1:seq                                 -- KW["prototypes"] _1,
   Component_Type_Extension.6:opt                                       -- _1,
   Component_Type_Extension.6:opt.1:seq                                 -- KW["features"] _1,
   Component_Type_Extension.7:opt                                       -- _1,
   Component_Type_Extension.7:opt.1:seq                                 -- KW["flows"] _1,
   Component_Type_Extension.8:opt                                       -- _1,
   Component_Type_Extension.9:opt                                       -- _1,
   Component_Type_Extension.9:opt.1:seq                                 -- KW["properties"] _1,
   Component_Type_Extension.10:opt                                      -- _1,
   Component_Type_Extension.10:opt.1:iter-star                          -- _1,
   abstract                                                             -- KW["abstract"],
   data                                                                 -- KW["data"],
   subprogram                                                           -- KW["subprogram"],
   subprogram_group                                                     -- KW["subprogram group"],
   thread                                                               -- KW["thread"],
   thread_group                                                         -- KW["thread group"],
   process                                                              -- KW["process"],
   system                                                               -- KW["system"],
   memory                                                               -- KW["memory"],
   bus                                                                  -- KW["bus"],
   processor                                                            -- KW["processor"],
   device                                                               -- KW["device"],
   virtual_processor                                                    -- KW["virtual processor"],
   virtual_bus                                                          -- KW["virtual bus"],
   CallSequencePropertyAssociations                                     -- V  [V vs=2 [KW["{"] _1] KW["}"]],
   CallSequencePropertyAssociations.1:iter                              -- _1,
   SubcomponentCallPropertyAssociations                                 -- V  [V vs=2 [KW["{"] _1] KW["}"]],
   SubcomponentCallPropertyAssociations.1:iter                          -- _1,
   SubprogramCallSequence                                               -- _1 KW[":"] KW["{"] _2 KW["}"] _3 _4 KW[";"],
   SubprogramCallSequence.2:iter                                        -- _1,
   SubprogramCallSequence.3:opt                                         -- _1,
   SubprogramCallSequence.4:opt                                         -- _1,
   SubprogramCall                                                       -- _1 KW[":"] KW["subprogram"] _2 _3 KW[";"],
   SubprogramCall.3:opt                                                 -- _1,
   CalledSubprogram                                                     -- _1,
   CalledSubprogram                                                     -- _1 KW["."] _2,
   CalledSubprogram                                                     -- _1 KW["."] _2,
   CalledSubprogram                                                     -- _1 KW["."] _2,
   CalledSubprogram                                                     -- _1 KW["."] _2,
   CalledSubprogram                                                     -- _1,
   CalledSubprogram                                                     -- KW["processor"] KW["."] _1,
   CalledSubprogram                                                     -- _1,
   CalledSubprogram                                                     -- _1 KW["."] _2,
   CalledSubprogram                                                     -- _1,
   CalledSubprogram                                                     -- _1 KW["."] _2,
   ComponentTypePropertyAssociation                                     -- _1,
   SubcomponentPropertyAssociation                                      -- _1,
   PrototypePropertyAssociation                                         -- _1,
   CallSequencePropertyAssociation                                      -- _1,
   SubcomponentCallPropertyAssociation                                  -- _1,
   ModeTransitionPropertyAssciation                                     -- _1,
   FeatureContainedPropertyAssociation                                  -- _1,
   ModePropertyAssciation                                               -- _1,
   ModeTransitionPropertyAssciation                                     -- _1,
   ConstantPropertyListValue                                            -- _1,
   ConstantPropertyListValue.1:iter-sep                                 -- _1 KW[","],
   BooleanPropertyConstantTerm                                          -- _1,
   StringPropertyConstantTerm                                           -- _1,
   EnumerationPropertyConstantTerm                                      -- _1,
   UnitPropertyConstantTerm                                             -- _1,
   IntegerRangePropertyConstantTerm                                     -- _1,
   RealRangePropertyConstantTerm                                        -- _1,
   IntegerPropertyConstantTerm                                          -- _1,
   IntegerPropertyConstantTerm                                          -- _1,
   BehaviorVariableDecls                                                -- V  [H  [KW["state"] KW["variables"]] _1],
   BehaviorVariableDecls.1:iter-star                                    -- _1,
   BehaviorStates                                                       -- V  [H  [KW["states"]] _1],
   BehaviorStates.1:iter                                                -- _1,
   AssignmentBs                                                         -- V  [H  [KW["initially"]] _1],
   AssignmentBs.1:iter-sep                                              -- _1 KW[";"],
   BehaviorStateTransitions                                             -- _1 KW["transitions "] _2,
   BehaviorStateTransitions.1:opt                                       -- _1,
   BehaviorStateTransitions.2:iter                                      -- _1,
   BehaviorAnnex                                                        -- _1 _2 _3 _4 _5,
   BehaviorAnnex.1:opt                                                  -- _1,
   BehaviorAnnex.2:opt                                                  -- _1,
   BehaviorAnnex.3:opt                                                  -- _1,
   BehaviorAnnex.4:opt                                                  -- _1,
   BehaviorAnnex.5:iter-star                                            -- _1,
   BehaviorVariableDecl                                                 -- _1 KW[":"] _2,
   BehaviorState                                                        -- _1 KW[":"] _2 KW["state"],
   BehaviorState.1:iter-star-sep                                        -- _1 KW[","],
   BehaviorState.2:iter-star                                            -- KW["initial"],
   BehaviorState                                                        -- _1 KW[":"] _2 KW["state"],
   BehaviorState.1:iter-star-sep                                        -- _1 KW[","],
   BehaviorState.2:iter-star                                            -- KW["complete"],
   BehaviorState                                                        -- _1 KW[":"] _2 KW["state"],
   BehaviorState.1:iter-star-sep                                        -- _1 KW[","],
   BehaviorState.2:iter-star                                            -- KW["return"],
   BehaviorState                                                        -- _1 KW[":"] _2 KW["state"],
   BehaviorState.1:iter-star-sep                                        -- _1 KW[","],
   BehaviorState.2:iter-star                                            -- KW["urgent"],
   BehaviorState                                                        -- _1 KW[":"] _2 KW["state"],
   BehaviorState.1:iter-star-sep                                        -- _1 KW[","],
   BehaviorState.2:iter-star                                            -- KW["composite"],
   BehaviorState                                                        -- _1 KW[":"] _2 KW["state"],
   BehaviorState.1:iter-star-sep                                        -- _1 KW[","],
   BehaviorState.2:iter-star                                            -- KW["exit"],
   DataClassifiers                                                      -- KW["("] _1 KW["in"] _2 KW[")"],
   BehaviorTransitionLabels                                             -- _1 _2 KW[":"],
   BehaviorTransitionLabels.2:opt                                       -- _1,
   BehaviorStateTransition                                              -- _1 _2 _3 KW["-["] _4 KW["]->"] _5 KW["{"] _6 KW["}"] KW[";"],
   BehaviorStateTransition.1:opt                                        -- _1,
   BehaviorStateTransition.2:opt                                        -- _1,
   BehaviorStateTransition.2:opt.1:seq                                  -- KW["["] _1 KW["]"],
   BehaviorStateTransition.3:iter-star-sep                              -- _1 KW[","],
   BehaviorStateTransition.6:iter-star                                  -- _1,
   BehaviorStateTransition                                              -- _1 _2 _3 KW["-["] _4 KW["]->"] _5 KW["{"] _6 KW["}"] KW[";"],
   BehaviorStateTransition.1:opt                                        -- _1,
   BehaviorStateTransition.2:opt                                        -- _1,
   BehaviorStateTransition.2:opt.1:seq                                  -- KW["["] _1 KW["]"],
   BehaviorStateTransition.3:iter-star-sep                              -- _1 KW[","],
   BehaviorStateTransition.6:iter-star                                  -- _1,
   BehaviorGuard                                                        -- _1 _2 _3,
   BehaviorGuard.1:opt                                                  -- _1,
   BehaviorGuard.1:opt.1:seq                                            -- KW["on"] _1 KW["-->"],
   BehaviorGuard.3:opt                                                  -- _1,
   BehaviorGuard.3:opt.1:seq                                            -- KW["when"] _1,
   BehaviorGuard                                                        -- _1,
   BehaviorEvent                                                        -- _1 KW["!"] _2,
   BehaviorEvent.2:opt                                                  -- _1,
   BehaviorEvent                                                        -- _1 KW["?"] _2,
   BehaviorEvent.2:opt                                                  -- _1,
   BehaviorParameterBindings                                            -- _1 _2 _3,
   BehaviorParameterBindings.2:opt                                      -- _1,
   BehaviorParameterBindings.2:opt.1:seq                                -- KW["->"] _1,
   BehaviorParameterBindings.3:iter-star                                -- _1,
   BehaviorParameterBindings.3:iter-star.1:seq                          -- KW[","] _1 _2,
   BehaviorParameterBindings.3:iter-star.1:seq.2:opt                    -- _1,
   BehaviorParameterBindings.3:iter-star.1:seq.2:opt.1:seq              -- KW["->"] _1,
   CompositeDeclaration                                                 -- KW["composite"] KW["history"] _1 KW["state"] _2 KW["transitions"] _3 _4 KW["end"] _5 KW[";"],
   CompositeDeclaration.1:opt                                           -- _1,
   CompositeDeclaration.1:opt.1:seq                                     -- KW["state"] _1,
   CompositeDeclaration.2:iter-star                                     -- _1,
   CompositeDeclaration.3:iter-star                                     -- _1,
   CompositeDeclaration.4:iter-star                                     -- _1,
   BehaviorExpression                                                   -- _1,
   BehaviorExpression.1:iter-sep                                        -- _1 KW["or"],
   Disjunction                                                          -- _1,
   Disjunction.1:iter-sep                                               -- _1 KW["and"],
   NotConjunction                                                       -- KW["not"] _1,
   Conjunction                                                          -- _1 _2,
   Conjunction.2:opt                                                    -- _1,
   Conjunction.2:opt.1:seq                                              -- KW["<"] _1,
   Conjunction                                                          -- _1 _2,
   Conjunction.2:opt                                                    -- _1,
   Conjunction.2:opt.1:seq                                              -- KW["<="] _1,
   Conjunction                                                          -- _1 _2,
   Conjunction.2:opt                                                    -- _1,
   Conjunction.2:opt.1:seq                                              -- KW["="] _1,
   Conjunction                                                          -- _1 _2,
   Conjunction.2:opt                                                    -- _1,
   Conjunction.2:opt.1:seq                                              -- KW[">"] _1,
   Conjunction                                                          -- _1 _2,
   Conjunction.2:opt                                                    -- _1,
   Conjunction.2:opt.1:seq                                              -- KW[">="] _1,
   Conjunction                                                          -- _1 _2,
   Conjunction.2:opt                                                    -- _1,
   Conjunction.2:opt.1:seq                                              -- KW["!="] _1,
   ArithExpression                                                      -- _1,
   ArithExpression.1:iter-sep                                           -- _1 KW["+"],
   ArithExpression                                                      -- _1,
   ArithExpression.1:iter-sep                                           -- _1 KW["-"],
   AddExpression                                                        -- _1,
   AddExpression.1:iter-sep                                             -- _1 KW["*"],
   AddExpression                                                        -- _1,
   AddExpression.1:iter-sep                                             -- _1 KW["/"],
   BasicExpression                                                      -- _1,
   BasicExpression                                                      -- _1,
   BasicExpression                                                      -- _1,
   BasicExpression                                                      -- _1,
   BasicExpression                                                      -- _1 KW["'"] _2,
   BasicExpression                                                      -- _1,
   BasicExpression                                                      -- _1,
   BasicExpression                                                      -- _1,
   BasicExpression                                                      -- _1 _2,
   BasicExpression.2:opt                                                -- _1,
   BasicExpression                                                      -- _1 KW["."] _2,
   BasicExpression                                                      -- _1 KW["."] _2,
   BasicExpression                                                      -- _1 KW["."] _2 _3,
   BasicExpression.3:iter-star-sep                                      -- _1 KW[","],
   BasicExpression                                                      -- _1 KW["."] _2 KW["?"] KW["("] _3 KW[")"],
   BasicExpression                                                      -- _1 KW["."] _2 KW["'"] _3,
   BasicExpression                                                      -- KW["("] _1 KW[")"],
   BasicExpression                                                      -- KW["("] _1 KW[")"],
   BasicExpression                                                      -- _1 KW["("] _2 KW["in"] _3 KW[")"] KW[":"] _4,
   count                                                                -- KW["count"],
   fresh                                                                -- KW["fresh"],
   all                                                                  -- KW["all"],
   exists                                                               -- KW["exists"],
   BehaviorAction                                                       -- _1,
   BehaviorAction                                                       -- _1 _2,
   BehaviorAction                                                       -- KW["if"] KW["("] _1 KW[")"] _2 _3 _4 KW["end"] KW["if"],
   BehaviorAction.3:iter-star                                           -- _1,
   BehaviorAction.4:opt                                                 -- _1,
   BehaviorAction.4:opt.1:seq                                           -- KW["else"] _1,
   BehaviorAction                                                       -- KW["for"] KW["("] _1 KW["in"] _2 KW[")"] KW["{"] _3 KW["}"],
   BehaviorAction                                                       -- KW["for"] KW["("] _1 KW["in"] _2 KW[")"] KW["{"] _3 KW["}"],
   Elsif                                                                -- KW["elsif"] KW["("] _1 KW[")"] _2,
   BasicAction                                                          -- KW["computation"] KW["("] _1 _2 KW[")"] KW[";"],
   BasicAction.2:opt                                                    -- _1,
   BasicAction.2:opt.1:seq                                              -- KW[","] _1,
   BasicAction                                                          -- KW["delay"] KW["("] _1 _2 KW[")"] KW[";"],
   BasicAction.2:opt                                                    -- _1,
   BasicAction.2:opt.1:seq                                              -- KW[","] _1,
   BasicAction                                                          -- _1,
   BasicAction                                                          -- _1,
   AssignmentB                                                          -- _1 KW[":="] _2,
   Communication                                                        -- _1 KW["?"] _2,
   Communication                                                        -- _1 KW["!"] _2,
   AnnexS_None                                                          -- KW["annex"] _1 KW["none"] _2 KW[";"],
   AnnexS_None.2:opt                                                    -- _1,
   AnnexS                                                               -- KW["annex"] _1 KW["{**"] _2 KW["**}"] _3 KW[";"],
   AnnexS.3:opt                                                         -- _1,
   AnnexL_None                                                          -- KW["annex"] _1 KW["none"] KW[";"],
   AnnexL                                                               -- KW["annex"] _1 KW["{**"] _2 KW["**}"] KW[";"],
   None                                                                 -- KW["modes"] KW["("] _1 KW[")"],
   Mode                                                                 -- KW["modes"] KW["("] _1 KW[")"],
   Mode.1:iter                                                          -- _1,
   ModeTransition                                                       -- KW["modes"] KW["("] _1 KW[")"],
   RequireNone                                                          -- KW["requires"] KW["modes"] KW["("] _1 KW[")"],
   RequireMode                                                          -- KW["requires"] KW["modes"] KW["("] _1 KW[")"],
   RequireMode.1:iter                                                   -- _1,
   Initial                                                              -- KW["initial"],
   ModePropertyAssciations                                              -- V  [V vs=2 [KW["{"] _1] KW["}"]],
   ModePropertyAssciations.1:iter                                       -- _1,
   ModeTransitionPropertyAssciations                                    -- V  [V vs=2 [KW["{"] _1] KW["}"]],
   ModeTransitionPropertyAssciations.1:iter                             -- _1,
   Mode                                                                 -- _1 KW[":"] _2 KW["mode"] _3 KW[";"],
   Mode.2:opt                                                           -- _1,
   Mode.3:opt                                                           -- _1,
   ModeTransition                                                       -- _1 _2 KW["-["] _3 KW["]->"] _4 _5 KW[";"],
   ModeTransition.1:opt                                                 -- _1,
   ModeTransition.1:opt.1:seq                                           -- _1 KW[":"],
   ModeTransition.3:iter-sep                                            -- _1 KW[","],
   ModeTransition.5:opt                                                 -- _1,
   SelfTtigger                                                          -- KW["self"] KW["."] _1,
   ProcessorTtigger                                                     -- KW["processor"] KW["."] _1,
   UniquePortIdentifier                                                 -- _1 _2,
   UniquePortIdentifier.1:opt                                           -- _1,
   UniquePortIdentifier.1:opt.1:seq                                     -- _1 KW["."],
   InMode                                                               -- KW["in"] KW["mode"] KW["("] _1 KW[")"],
   InMode.1:iter-sep                                                    -- _1 KW[","],
   Component                                                            -- KW["in"] KW["mode"] KW["("] _1 KW[")"],
   Component.1:iter-sep                                                 -- _1 KW[","],
   ModeName                                                             -- _1 _2,
   ModeName.2:seq                                                       -- KW["=>"] _1,
   InModesAndTransitions                                                -- KW["in"] KW["mode"] KW["("] _1 KW[")"],
   InModesAndTransitions.1:iter-sep                                     -- _1 KW[","],
   FeatureGroupConnection                                               -- KW["feature"] KW["group"] _1 _2 _3,
   feature_group                                                        -- KW["feature"] KW["group"],
   ComponentTypeFeatureGroupIdentifier                                  -- _1,
   SubcomponentIdentifier_FeatureGroupIdentifier                        -- _1 KW["."] _2,
   ComponentTypeFeatureGroupIdentifier_ElementFeatureGroupIdentifier    -- _1 KW["."] _2,
   AccessConnection                                                     -- _1 KW["access"] _2 _3 _4,
   access                                                               -- _1 KW["access"],
   RequiresAccessIdentifier                                             -- _1,
   ProvidesAccessIdentifier                                             -- _1,
   FeatureGroupIdentifier_RequiresAccessIdentifier                      -- _1 KW["."] _2,
   FeatureGroupIdentifier_ProvidesAccessIdentifier                      -- _1 KW["."] _2,
   SubcomponentIdentifier_ProvidesAccessIdentifier                      -- _1 KW["."] _2,
   SubcomponentIdentifier_RequiresAccessIdentifier                      -- _1 KW["."] _2,
   SubprogramCallIdentifier_requiresOrProvidesAccessIdentifier          -- _1 KW["."] _2,
   SubcomponentIdentifier                                               -- _1,
   processor_ProvidesSubprogramAccessIdentifier                         -- KW["processor"] KW["."] _1,
   ParameterConnection                                                  -- KW["parameter"] _1 _2 _3,
   parameter                                                            -- KW["parameter"],
   ComponentTypeParameterIdentifier                                     -- _1 _2,
   ComponentTypeParameterIdentifier.2:opt                               -- _1,
   ComponentTypeParameterIdentifier.2:opt.1:seq                         -- KW["."] _1,
   SubprogramCallIdentifier_ParameterIdentifier                         -- _1 KW["."] _2,
   ComponentTypePortIdentifier                                          -- _1 _2,
   ComponentTypePortIdentifier.2:opt                                    -- _1,
   ComponentTypePortIdentifier.2:opt.1:seq                              -- KW["."] _1,
   DataSubcomponentIdentifier                                           -- _1,
   RequiresDataAccessIdentifier                                         -- _1,
   ComponentTypeFeatureGroupIdentifier_ElementDataAccessIdentifier      -- _1 KW["."] _2,
   ComponentTypeFeatureGroupIdentifier_ElementPortOrParameterIdentifier -- _1 KW["."] _2,
   PortConnection                                                       -- KW["port"] _1 _2 _3,
   port                                                                 -- KW["port"],
   ComponentTypePortIdentifier                                          -- _1,
   SubcomponentIdentifier_PortIdentifier                                -- _1 KW["."] _2,
   ComponentTypeFeatureGroupIdentifier_ElementPortIdentifier            -- _1 KW["."] _2,
   ComponentTypePortIdentifier_DataSubcomponentIdentifier               -- _1 KW["."] _2,
   ComponentTypeRequiresDataAccessIdentifier                            -- _1,
   DataSubcomponentIdentifier                                           -- _1,
   SubcomponentIdentifier_ProvidesDataAccessIdentifier                  -- _1 KW["."] _2,
   ComponentTypeFeatureGroupIdentifier_ElementDataAccessIdentifier      -- _1 KW["."] _2,
   DataSubcomponentIdentifier_DataSubcomponentIdentifier                -- _1 KW["."] _2,
   ProcessorPortIdentifier                                              -- KW["processor"] KW["."] _1,
   EventOrEventDataSourceIdentifier                                     -- KW["self"] KW["."] _1,
   FeatureConnection                                                    -- KW["feature"] _1 _2 _3,
   DConnectionSymbol                                                    -- _1,
   BConnectionSymbol                                                    -- _1,
   DirectionalConnectionSymbol                                          -- KW["->"],
   BidirectionalConnectionSymbol                                        -- KW["<->"],
   ComponentTypeFeatureGroupIdentifier_FeatureIdentifier                -- _1 KW["."] _2,
   SubcomponentIdentifier_FeatureIdentifier                             -- _1 KW["."] _2,
   SubprogramCallIdentifier_FeatureIdentifier                           -- _1 KW["."] _2,
   feature                                                              -- KW["feature"],
   PropertyAssociationes                                                -- V  [V vs=2 [KW["{"] _1] KW["}"]],
   PropertyAssociationes.1:iter                                         -- _1,
   FeatureConnection                                                    -- _1 KW[":"] _2 _3 _4 KW[";"],
   FeatureConnection.3:opt                                              -- _1,
   FeatureConnection.4:opt                                              -- _1,
   PortConnection                                                       -- _1 KW[":"] _2 _3 _4 KW[";"],
   PortConnection.3:opt                                                 -- _1,
   PortConnection.4:opt                                                 -- _1,
   ParameterConnection                                                  -- _1 KW[":"] _2 _3 _4 KW[";"],
   ParameterConnection.3:opt                                            -- _1,
   ParameterConnection.4:opt                                            -- _1,
   AccessConnection                                                     -- _1 KW[":"] _2 _3 _4 KW[";"],
   AccessConnection.3:opt                                               -- _1,
   AccessConnection.4:opt                                               -- _1,
   FeatureGroupConnection                                               -- _1 KW[":"] _2 _3 _4 KW[";"],
   FeatureGroupConnection.3:opt                                         -- _1,
   FeatureGroupConnection.4:opt                                         -- _1,
   FeatureConnectionRefinement                                          -- _1 KW[":"] KW["refined"] KW["to"] _2 _3 _4 KW[";"],
   FeatureConnectionRefinement.3:opt                                    -- _1,
   FeatureConnectionRefinement.4:opt                                    -- _1,
   PortConnectionRefinement                                             -- _1 KW[":"] KW["refined"] KW["to"] _2 _3 _4 KW[";"],
   PortConnectionRefinement.3:opt                                       -- _1,
   PortConnectionRefinement.4:opt                                       -- _1,
   ParameterConnectionRefinement                                        -- _1 KW[":"] KW["refined"] KW["to"] _2 _3 _4 KW[";"],
   ParameterConnectionRefinement.3:opt                                  -- _1,
   ParameterConnectionRefinement.4:opt                                  -- _1,
   AccessConnectionRefinement                                           -- _1 KW[":"] KW["refined"] KW["to"] _2 _3 _4 KW[";"],
   AccessConnectionRefinement.3:opt                                     -- _1,
   AccessConnectionRefinement.4:opt                                     -- _1,
   FeatureGroupConnectionRefinement                                     -- _1 KW[":"] KW["refined"] KW["to"] _2 _3 _4 KW[";"],
   FeatureGroupConnectionRefinement.3:opt                               -- _1,
   FeatureGroupConnectionRefinement.4:opt                               -- _1,
   FlowSourceSpec                                                       -- _1 KW[":"] KW["flow"] KW["source"] _2 _3 _4 KW[";"],
   FlowSourceSpec.3:opt                                                 -- _1,
   FlowSourceSpec.4:opt                                                 -- _1,
   FlowSinkSpec                                                         -- _1 KW[":"] KW["flow"] KW["sink"] _2 _3 _4 KW[";"],
   FlowSinkSpec.3:opt                                                   -- _1,
   FlowSinkSpec.4:opt                                                   -- _1,
   FlowPathSpec                                                         -- _1 KW[":"] KW["flow"] KW["path"] _2 KW["->"] _3 _4 _5 KW[";"],
   FlowPathSpec.4:opt                                                   -- _1,
   FlowPathSpec.5:opt                                                   -- _1,
   FlowSourceSpecRefinement                                             -- _1 KW[":"] KW["refined"] KW["to"] KW["flow"] KW["source"] _2 _3 KW[";"],
   FlowSourceSpecRefinement.2:opt                                       -- _1,
   FlowSourceSpecRefinement.3:opt                                       -- _1,
   FlowSourceSpecRefinement                                             -- _1 KW[":"] KW["refined"] KW["to"] KW["flow"] KW["source"] _2 KW[";"],
   FlowSourceSpecRefinement.2:opt                                       -- _1,
   FlowSinkSpecRefinement                                               -- _1 KW[":"] KW["refined"] KW["to"] KW["flow"] KW["sink"] _2 _3 KW[";"],
   FlowSinkSpecRefinement.2:opt                                         -- _1,
   FlowSinkSpecRefinement.3:opt                                         -- _1,
   FlowSinkSpecRefinement                                               -- _1 KW[":"] KW["refined"] KW["to"] KW["flow"] KW["sink"] _2 KW[";"],
   FlowSinkSpecRefinement.2:opt                                         -- _1,
   FlowPathSpecRefinement                                               -- _1 KW[":"] KW["refined"] KW["to"] KW["flow"] KW["path"] _2 _3 KW[";"],
   FlowPathSpecRefinement.2:opt                                         -- _1,
   FlowPathSpecRefinement.3:opt                                         -- _1,
   FlowPathSpecRefinement                                               -- _1 KW[":"] KW["refined"] KW["to"] KW["flow"] KW["path"] _2 KW[";"],
   FlowPathSpecRefinement.2:opt                                         -- _1,
   Com                                                                  -- _1 KW["."] _2,
   Com                                                                  -- _1 KW["."] _2,
   ProvidesBusAccessSpecReference                                       -- _1 KW[":"] KW["provides"] KW["bus"] KW["access"] _2,
   RequiresBusAccessSpecReference                                       -- _1 KW[":"] KW["requires"] KW["bus"] KW["access"] _2,
   ProvidesBusAccessSpecIdentifier                                      -- _1 KW[":"] KW["provides"] KW["bus"] KW["access"] _2,
   RequiresBusAccessSpecIdentifier                                      -- _1 KW[":"] KW["requires"] KW["bus"] KW["access"] _2,
   ProvidesBusAccessRefinementReference                                 -- _1 KW[":"] KW["refined"] KW["to"] KW["provides"] KW["bus"] KW["access"] _2,
   RequiresBusAccessRefinementReference                                 -- _1 KW[":"] KW["refined"] KW["to"] KW["requires"] KW["bus"] KW["access"] _2,
   ProvidesBusAccessRefinementIdentifier                                -- _1 KW[":"] KW["refined"] KW["to"] KW["provides"] KW["bus"] KW["access"] _2,
   RequiresBusAccessRefinementIdentifier                                -- _1 KW[":"] KW["refined"] KW["to"] KW["requires"] KW["bus"] KW["access"] _2,
   ProvidesDataAccessSpecReference                                      -- _1 KW[":"] KW["provides"] KW["data"] KW["access"] _2,
   RequiresDataAccessSpecReference                                      -- _1 KW[":"] KW["requires"] KW["data"] KW["access"] _2,
   ProvidesDataAccessSpecIdentifier                                     -- _1 KW[":"] KW["provides"] KW["data"] KW["access"] _2,
   RequiresDataAccessSpecIdentifier                                     -- _1 KW[":"] KW["requires"] KW["data"] KW["access"] _2,
   ProvidesDataAccessRefinementReference                                -- _1 KW[":"] KW["refined"] KW["to"] KW["provides"] KW["data"] KW["access"] _2,
   RequiresDataAccessRefinementReference                                -- _1 KW[":"] KW["refined"] KW["to"] KW["requires"] KW["data"] KW["access"] _2,
   ProvidesDataAccessRefinementIdentifier                               -- _1 KW[":"] KW["refined"] KW["to"] KW["provides"] KW["data"] KW["access"] _2,
   RequiresDataAccessRefinementIdentifier                               -- _1 KW[":"] KW["refined"] KW["to"] KW["requires"] KW["data"] KW["access"] _2,
   ProvidesSubprogramAccessSpecReference                                -- _1 KW[":"] KW["provides"] KW["subprogram"] KW["access"] _2,
   ProvidesSubprogramAccessSpecReference.2:opt                          -- _1,
   RequiresSubprogramAccessSpecReference                                -- _1 KW[":"] KW["requires"] KW["subprogram"] KW["access"] _2,
   RequiresSubprogramAccessSpecReference.2:opt                          -- _1,
   ProvidesSubprogramAccessSpecIdentifier                               -- _1 KW[":"] KW["provides"] KW["subprogram"] KW["access"] _2,
   ProvidesSubprogramAccessSpecIdentifier.2:opt                         -- _1,
   RequiresSubprogramAccessSpecIdentifier                               -- _1 KW[":"] KW["requires"] KW["subprogram"] KW["access"] _2,
   RequiresSubprogramAccessSpecIdentifier.2:opt                         -- _1,
   ProvidesSubprogramAccessRefinementReference                          -- _1 KW[":"] KW["refined"] KW["to"] KW["provides"] KW["subprogram"] KW["access"] _2,
   ProvidesSubprogramAccessRefinementReference.2:opt                    -- _1,
   RequiresSubprogramAccessRefinementReference                          -- _1 KW[":"] KW["refined"] KW["to"] KW["requires"] KW["subprogram"] KW["access"] _2,
   RequiresSubprogramAccessRefinementReference.2:opt                    -- _1,
   ProvidesSubprogramAccessRefinementIdentifier                         -- _1 KW[":"] KW["refined"] KW["to"] KW["provides"] KW["subprogram"] KW["access"] _2,
   ProvidesSubprogramAccessRefinementIdentifier.2:opt                   -- _1,
   RequiresSubprogramAccessRefinementIdentifier                         -- _1 KW[":"] KW["refined"] KW["to"] KW["requires"] KW["subprogram"] KW["access"] _2,
   RequiresSubprogramAccessRefinementIdentifier.2:opt                   -- _1,
   ProvidesSubprogramGroupAccessSpecReference                           -- _1 KW[":"] KW["provides"] KW["subprogram"] KW["group"] KW["access"] _2,
   ProvidesSubprogramGroupAccessSpecReference.2:opt                     -- _1,
   RequiresSubprogramGroupAccessSpecReference                           -- _1 KW[":"] KW["requires"] KW["subprogram"] KW["group"] KW["access"] _2,
   RequiresSubprogramGroupAccessSpecReference.2:opt                     -- _1,
   ProvidesSubprogramGroupAccessSpecIdentifier                          -- _1 KW[":"] KW["provides"] KW["subprogram"] KW["group"] KW["access"] _2,
   ProvidesSubprogramGroupAccessSpecIdentifier.2:opt                    -- _1,
   RequiresSubprogramGroupAccessSpecIdentifier                          -- _1 KW[":"] KW["requires"] KW["subprogram"] KW["group"] KW["access"] _2,
   RequiresSubprogramGroupAccessSpecIdentifier.2:opt                    -- _1,
   ProvidesSubprogramGroupAccessRefinementReference                     -- _1 KW[":"] KW["refined"] KW["to"] KW["provides"] KW["subprogram"] KW["group"] KW["access"] _2,
   ProvidesSubprogramGroupAccessRefinementReference.2:opt               -- _1,
   RequiresSubprogramGroupAccessRefinementReference                     -- _1 KW[":"] KW["refined"] KW["to"] KW["requires"] KW["subprogram"] KW["group"] KW["access"] _2,
   RequiresSubprogramGroupAccessRefinementReference.2:opt               -- _1,
   ProvidesSubprogramGroupAccessRefinementIdentifier                    -- _1 KW[":"] KW["refined"] KW["to"] KW["provides"] KW["subprogram"] KW["group"] KW["access"] _2,
   ProvidesSubprogramGroupAccessRefinementIdentifier.2:opt              -- _1,
   RequiresSubprogramGroupAccessRefinementIdentifier                    -- _1 KW[":"] KW["refined"] KW["to"] KW["requires"] KW["subprogram"] KW["group"] KW["access"] _2,
   RequiresSubprogramGroupAccessRefinementIdentifier.2:opt              -- _1,
   ParameterSpecReference                                               -- _1 KW[":"] _2 KW["parameter"] _3,
   ParameterSpecIdentifier                                              -- _1 KW[":"] _2 KW["parameter"] _3,
   ParameterRefinementReference                                         -- _1 KW[":"] KW["refined"] KW["to"] _2 KW["parameter"] _3,
   ParameterRefinementIdentifier                                        -- _1 KW[":"] KW["refined"] KW["to"] _2 KW["parameter"] _3,
   PortSpec                                                             -- _1 KW[":"] _2 _3,
   PortRefinement                                                       -- _1 KW[":"] KW["refined"] KW["to"] _2 _3,
   DataReference                                                        -- KW["data"] KW["port"] _1,
   DataReference.1:opt                                                  -- _1,
   DataIdentifier                                                       -- KW["data"] KW["port"] _1,
   DataIdentifier.1:opt                                                 -- _1,
   EventDataReference                                                   -- KW["event"] KW["data"] KW["port"] _1,
   EventDataReference.1:opt                                             -- _1,
   EventDataIdentifier                                                  -- KW["event"] KW["data"] KW["port"] _1,
   EventDataIdentifier.1:opt                                            -- _1,
   EventIdentifier                                                      -- KW["event"] KW["port"],
   In_AbstractFeatureSpec                                               -- _1 KW[":"] KW["in"] KW["feature"] _2,
   In_AbstractFeatureSpec.2:opt                                         -- _1,
   Out_AbstractFeatureSpec                                              -- _1 KW[":"] KW["out"] KW["feature"] _2,
   Out_AbstractFeatureSpec.2:opt                                        -- _1,
   In_AbstractFeatureRefinement                                         -- _1 KW[":"] KW["refined"] KW["to"] KW["in"] KW["feature"] _2,
   In_AbstractFeatureRefinement.2:opt                                   -- _1,
   Out_AbstractFeatureRefinement                                        -- _1 KW[":"] KW["refined"] KW["to"] KW["out"] KW["feature"] _2,
   Out_AbstractFeatureRefinement.2:opt                                  -- _1,
   Inherit                                                              -- KW["inherit"],
   PropertyDefinitionDeclaration                                        -- _1 KW[":"] _2 _3 KW["applies"] KW["to"] KW["("] _4 KW[")"] KW[";"],
   PropertyDefinitionDeclaration.2:opt                                  -- _1,
   PropertyDefinitionDeclaration.4:iter-sep                             -- _1 KW[","],
   PropertyDefinitionDeclaration                                        -- _1 KW[":"] _2 _3 KW["applies"] KW["to"] KW["("] _4 KW[")"] KW[";"],
   PropertyDefinitionDeclaration.2:opt                                  -- _1,
   PropertyDefinitionDeclaration.4:iter-sep                             -- _1 KW[","],
   SingleValuedProperty                                                 -- _1 _2,
   SingleValuedProperty.2:opt                                           -- _1,
   SingleValuedProperty.2:opt.1:seq                                     -- KW["=>"] _1,
   MultiValuedProperty                                                  -- _1 _2 _3,
   MultiValuedProperty.1:iter                                           -- _1,
   MultiValuedProperty.1:iter.1:seq                                     -- KW["list"] KW["of"],
   MultiValuedProperty.3:opt                                            -- _1,
   MultiValuedProperty.3:opt.1:seq                                      -- KW["=>"] _1,
   SingleValuedPropertyConstant                                         -- _1 KW[":"] KW["constant"] _2 KW["=>"] _3,
   MultiValuedPropertyConstant                                          -- _1 KW[":"] KW["constant"] _2 _3 KW["=>"] _4,
   MultiValuedPropertyConstant.2:iter                                   -- _1,
   MultiValuedPropertyConstant.2:iter.1:seq                             -- KW["list"] KW["of"],
   UniquePropertyConstantIdentifier                                     -- _1 _2,
   UniquePropertyConstantIdentifier.1:opt                               -- _1,
   UniquePropertyConstantIdentifier.1:opt.1:seq                         -- _1 KW["::"],
   Property_Type_Declaration                                            -- _1 KW[":"] KW["type"] _2 KW[";"],
   Property_Type                                                        -- KW["aadlboolean"],
   Property_Type                                                        -- KW["aadlstring"],
   Property_Type                                                        -- _1,
   Property_Type                                                        -- _1,
   Property_Type                                                        -- _1,
   Property_Type                                                        -- _1,
   Property_Type                                                        -- _1,
   Property_Type                                                        -- _1,
   Property_Type                                                        -- _1,
   Enumeration_Type                                                     -- KW["enumeration"] KW["("] _1 KW[")"],
   Enumeration_Type.1:iter-sep                                          -- _1 KW[","],
   Units_Type                                                           -- KW["units"] _1,
   Units_List                                                           -- KW["("] _1 _2 KW[")"],
   Units_List.2:iter-star                                               -- _1,
   Units_List.2:iter-star.1:seq                                         -- KW[","] _1 KW["=>"] _2 KW["*"] _3,
   Number_Type                                                          -- KW["aadlreal"] _1 _2,
   Number_Type.1:opt                                                    -- _1,
   Number_Type.2:opt                                                    -- _1,
   Number_Type.2:opt.1:seq                                              -- KW["units"] _1,
   Number_Type                                                          -- KW["aadinteger"] _1 _2,
   Number_Type.1:opt                                                    -- _1,
   Number_Type.2:opt                                                    -- _1,
   Number_Type.2:opt.1:seq                                              -- KW["units"] _1,
   Real_Range                                                           -- _1 KW[".."] _2,
   Integer_Range                                                        -- _1 KW[".."] _2,
   SignedAadlrealOrConstant                                             -- _1 _2,
   SignedAadlrealOrConstant.1:opt                                       -- _1,
   SignedAadlintegerOrConstant                                          -- _1 _2,
   SignedAadlintegerOrConstant.1:opt                                    -- _1,
   positive                                                             -- KW["+"],
   negative                                                             -- KW["-"],
   Signed_Aadlinteger                                                   -- _1 _2 _3,
   Signed_Aadlinteger.1:opt                                             -- _1,
   Signed_Aadlinteger.3:opt                                             -- _1,
   Signed_Aadlreal                                                      -- _1 _2 _3,
   Signed_Aadlreal.1:opt                                                -- _1,
   Signed_Aadlreal.3:opt                                                -- _1,
   RangeType                                                            -- KW["range"] KW["of"] _1,
   RangeType                                                            -- KW["range"] KW["of"] _1,
   ClassifierCategoryReferences                                         -- KW["("] _1 KW[")"],
   ClassifierCategoryReferences.1:iter-sep                              -- _1 KW[","],
   ReferenceCategorys                                                   -- KW["("] _1 KW[")"],
   ReferenceCategorys.1:iter-sep                                        -- _1 KW[","],
   ListOf                                                               -- KW["list"] KW["of"],
   Classifier_Type                                                      -- KW["classifier"] _1,
   Classifier_Type.1:opt                                                -- _1,
   QualifiedMetaModelIdentifier                                         -- _1 _2,
   QualifiedMetaModelIdentifier.1:opt                                   -- _1,
   QualifiedMetaModelIdentifier.1:opt.1:seq                             -- KW["{"] _1 KW["}"] KW["**"],
   MetaModelClassIdentifier                                             -- _1,
   MetaModelClassIdentifier.1:iter                                      -- _1,
   ReferenceType                                                        -- KW["reference"] _1,
   ReferenceType.1:opt                                                  -- _1,
   UniquePropertyTypeIdentifier                                         -- _1 _2,
   UniquePropertyTypeIdentifier.1:opt                                   -- _1,
   UniquePropertyTypeIdentifier.1:opt.1:seq                             -- _1 KW["::"],
   RecordType                                                           -- KW["record"] KW["("] _1 KW[")"],
   RecordType.1:iter                                                    -- _1,
   RecordField                                                          -- _1 KW[":"] _2 _3,
   RecordField.2:opt                                                    -- _1,
   Not                                                                  -- KW["not"] _1,
   And                                                                  -- _1 KW["and"] _2,
   Or                                                                   -- _1 KW["or"] _2,
   BooleanTerm                                                          -- KW["("] _1 KW[")"],
   True                                                                 -- KW["true"],
   False                                                                -- KW["false"],
   IntegerRangeTerm                                                     -- _1 KW[".."] _2 _3,
   IntegerRangeTerm.3:opt                                               -- _1,
   IntegerRangeTerm.3:opt.1:seq                                         -- KW["data"] _1,
   IntegerRangeTerm                                                     -- _1,
   RealRangeTerm                                                        -- _1 KW[".."] _2 _3,
   RealRangeTerm.3:opt                                                  -- _1,
   RealRangeTerm.3:opt.1:seq                                            -- KW["data"] _1,
   RealRangeTerm                                                        -- _1,
   PropertyTerm                                                         -- _1 _2,
   PropertyTerm.1:seq                                                   -- _1 KW["::"],
   PropertyConstantTerm                                                 -- _1 _2,
   PropertyConstantTerm.1:seq                                           -- _1 KW["::"],
   ComponentClassifierTerm                                              -- KW["classifier"] KW["("] _1 KW[")"],
   ReferenceTerm                                                        -- KW["reference"] KW["("] _1 KW[")"],
   RecordTerm                                                           -- V  [V vs=2 [KW["("] _1] KW[")"]],
   RecordTerm.1:iter                                                    -- _1,
   RecordTerm.1:iter.1:seq                                              -- _1 KW["=>"] _2 KW[";"],
   ComputedTerm                                                         -- KW["compute"] KW["("] _1 KW[")"],
   UniqueComponentClassifierReferences                                  -- _1 _2,
   ArrayDimensionses                                                    -- _1 _2,
   SubcomponentPropertyAssociations                                     -- V  [V vs=2 [KW["{"] _1] KW["}"]],
   SubcomponentPropertyAssociations.1:iter                              -- _1,
   ContainedPropertyAssociations                                        -- V  [V vs=2 [KW["{"] _1] KW["}"]],
   ContainedPropertyAssociations.1:iter                                 -- _1,
   Subcomponent                                                         -- _1 KW[":"] _2 _3 _4 _5 _6,
   Subcomponent.3:opt                                                   -- _1,
   Subcomponent.4:opt                                                   -- _1,
   Subcomponent.5:opt                                                   -- _1,
   Subcomponent.6:opt                                                   -- _1,
   Subcomponent                                                         -- _1 KW[":"] _2 _3 _4 _5 _6,
   Subcomponent.3:opt                                                   -- _1,
   Subcomponent.4:opt                                                   -- _1,
   Subcomponent.5:opt                                                   -- _1,
   Subcomponent.6:opt                                                   -- _1,
   Subcomponent                                                         -- _1 KW[":"] _2 _3 _4 _5 _6,
   Subcomponent.3:opt                                                   -- _1,
   Subcomponent.4:opt                                                   -- _1,
   Subcomponent.5:opt                                                   -- _1,
   Subcomponent.6:opt                                                   -- _1,
   Subcomponent                                                         -- _1 KW[":"] _2 _3 _4 _5 _6,
   Subcomponent.3:opt                                                   -- _1,
   Subcomponent.4:opt                                                   -- _1,
   Subcomponent.5:opt                                                   -- _1,
   Subcomponent.6:opt                                                   -- _1,
   Subcomponent_Refinement                                              -- _1 KW[":"] KW["refined to"] _2 _3 _4 _5 _6,
   Subcomponent_Refinement.3:opt                                        -- _1,
   Subcomponent_Refinement.4:opt                                        -- _1,
   Subcomponent_Refinement.5:opt                                        -- _1,
   Subcomponent_Refinement.6:opt                                        -- _1,
   Subcomponent_Refinement                                              -- _1 KW[":"] KW["refined to"] _2 _3 _4 _5 _6,
   Subcomponent_Refinement.3:opt                                        -- _1,
   Subcomponent_Refinement.4:opt                                        -- _1,
   Subcomponent_Refinement.5:opt                                        -- _1,
   Subcomponent_Refinement.6:opt                                        -- _1,
   Subcomponent_Refinement                                              -- _1 KW[":"] KW["refined to"] _2 _3 _4 _5 _6,
   Subcomponent_Refinement.3:opt                                        -- _1,
   Subcomponent_Refinement.4:opt                                        -- _1,
   Subcomponent_Refinement.5:opt                                        -- _1,
   Subcomponent_Refinement.6:opt                                        -- _1,
   Subcomponent_Refinement                                              -- _1 KW[":"] KW["refined to"] _2 _3 _4 _5 _6,
   Subcomponent_Refinement.3:opt                                        -- _1,
   Subcomponent_Refinement.4:opt                                        -- _1,
   Subcomponent_Refinement.5:opt                                        -- _1,
   Subcomponent_Refinement.6:opt                                        -- _1,
   ArrayDimensions                                                      -- _1,
   ArrayDimensions.1:iter                                               -- _1,
   ArrayDimension                                                       -- KW["["] _1 KW["]"],
   ArrayDimension.1:opt                                                 -- _1,
   StrCon                                                               -- KW["("] _1 _2 _3 KW[")"],
   StrCon.2:opt                                                         -- _1,
   StrCon.3:iter-star                                                   -- _1,
   StrCon.3:iter-star.1:seq                                             -- KW[","] _1 _2,
   StrCon.3:iter-star.1:seq.2:opt                                       -- _1,
   ArraySelectionName                                                   -- _1 _2,
   ArraySelection                                                       -- _1,
   ArraySelection.1:iter                                                -- _1,
   ArraySelection.1:iter.1:seq                                          -- KW["["] _1 KW["]"],
   SelectionRange                                                       -- _1 _2,
   SelectionRange.2:opt                                                 -- _1,
   SelectionRange.2:opt.1:seq                                           -- KW[".."] _1,
   FeatureContainedPropertyAssociations                                 -- V  [V vs=2 [KW["{"] _1] KW["}"]],
   FeatureContainedPropertyAssociations.1:iter                          -- _1,
   AbstractFeatureSpec                                                  -- _1 _2 _3 KW[";"],
   AbstractFeatureSpec.2:opt                                            -- _1,
   AbstractFeatureSpec.3:opt                                            -- _1,
   PortSpec                                                             -- _1 _2 _3 KW[";"],
   PortSpec.2:opt                                                       -- _1,
   PortSpec.3:opt                                                       -- _1,
   FeatureGroupSpec                                                     -- _1 _2 _3 KW[";"],
   FeatureGroupSpec.2:opt                                               -- _1,
   FeatureGroupSpec.3:opt                                               -- _1,
   SubcomponentAccessSpec                                               -- _1 _2 _3 KW[";"],
   SubcomponentAccessSpec.2:opt                                         -- _1,
   SubcomponentAccessSpec.3:opt                                         -- _1,
   ParameterSpec                                                        -- _1 _2 _3 KW[";"],
   ParameterSpec.2:opt                                                  -- _1,
   ParameterSpec.3:opt                                                  -- _1,
   AbstractFeatureRefinement                                            -- _1 _2 _3 KW[";"],
   AbstractFeatureRefinement.2:opt                                      -- _1,
   AbstractFeatureRefinement.3:opt                                      -- _1,
   PortRefinement                                                       -- _1 _2 _3 KW[";"],
   PortRefinement.2:opt                                                 -- _1,
   PortRefinement.3:opt                                                 -- _1,
   FeatureGroupRefinement                                               -- _1 _2 _3 KW[";"],
   FeatureGroupRefinement.2:opt                                         -- _1,
   FeatureGroupRefinement.3:opt                                         -- _1,
   SubcomponentAccessRefinement                                         -- _1 _2 _3 KW[";"],
   SubcomponentAccessRefinement.2:opt                                   -- _1,
   SubcomponentAccessRefinement.3:opt                                   -- _1,
   ParameterRefinement                                                  -- _1 _2 _3 KW[";"],
   ParameterRefinement.2:opt                                            -- _1,
   ParameterRefinement.3:opt                                            -- _1,
   PrototypePropertyAssociations                                        -- V  [V vs=2 [KW["{"] _1] KW["}"]],
   PrototypePropertyAssociations.1:iter                                 -- _1,
   Brackets                                                             -- KW["["] KW["]"],
   Component_Prototype                                                  -- _1 KW[":"] _2 _3 KW[";"],
   Component_Prototype.3:opt                                            -- _1,
   FeatureGroupType_Prototype                                           -- _1 KW[":"] _2 _3 KW[";"],
   FeatureGroupType_Prototype.3:opt                                     -- _1,
   Feature_Prototype                                                    -- _1 KW[":"] _2 _3 KW[";"],
   Feature_Prototype.3:opt                                              -- _1,
   ComponentPrototype                                                   -- _1 _2 _3,
   ComponentPrototype.2:opt                                             -- _1,
   ComponentPrototype.3:opt                                             -- _1,
   FeatureGroupTypePrototype                                            -- KW["feature"] KW["group"] _1,
   FeatureGroupTypePrototype.1:opt                                      -- _1,
   FeaturePrototype                                                     -- KW["in"] KW["featute"] _1,
   FeaturePrototype.1:opt                                               -- _1,
   Component_Prototype_Refinement                                       -- _1 KW[":"] KW["refinied"] KW["to"] _2 _3 KW[";"],
   Component_Prototype_Refinement.3:opt                                 -- _1,
   FeatureGroupType_Prototype_Refinement                                -- _1 KW[":"] KW["refinied"] KW["to"] _2 _3 KW[";"],
   FeatureGroupType_Prototype_Refinement.3:opt                          -- _1,
   Feature_Prototype_Refinement                                         -- _1 KW[":"] KW["refinied"] KW["to"] _2 _3 KW[";"],
   Feature_Prototype_Refinement.3:opt                                   -- _1,
   PrototypeBindings                                                    -- KW["("] _1 KW[")"],
   PrototypeBindings.1:iter-sep                                         -- _1 KW[","],
   PrototypeBinding                                                     -- _1 KW["=>"] _2,
   PrototypeBinding                                                     -- _1 KW["=>"] _2,
   PrototypeBinding                                                     -- _1 KW["=>"] _2,
   PrototypeBinding                                                     -- _1 KW["=>"] _2,
   ComponentPrototypeActual                                             -- _1 _2 _3,
   ComponentPrototypeActual.3:opt                                       -- _1,
   ComponentPrototypeActual                                             -- _1 _2,
   ComponentPrototypeActualList                                         -- KW["("] _1 KW[")"],
   ComponentPrototypeActualList.1:iter-sep                              -- _1 KW[","],
   FeatureGroupTypePrototypeActual                                      -- KW["feature"] KW["group"] _1 _2,
   FeatureGroupTypePrototypeActual.2:opt                                -- _1,
   FeatureGroupTypePrototypeActual                                      -- KW["feature"] KW["group"] _1,
   In                                                                   -- KW["in"],
   Out                                                                  -- KW["out"],
   In_Out                                                               -- KW["in"] KW["out"],
   Event                                                                -- KW["event"],
   Data                                                                 -- KW["data"],
   Event_Data                                                           -- KW["event"] KW["data"],
   Bus                                                                  -- KW["bus"],
   Data                                                                 -- KW["data"],
   Subprogram                                                           -- KW["subprogram"],
   Subprogram_Group                                                     -- KW["subprogram"] KW["group"],
   Port                                                                 -- _1 _2 KW["port"],
   Requires_Access                                                      -- KW["requires"] _1 KW["access"] _2,
   Requires_Access.2:opt                                                -- _1,
   Provides_Access                                                      -- KW["provides"] _1 KW["access"] _2,
   Provides_Access.2:opt                                                -- _1,
   In_Feature                                                           -- KW["in"] KW["feature"] _1,
   Out_Feature                                                          -- KW["out"] KW["feature"] _1,
   ComponentTypeIdentifier                                              -- _1 _2,
   ComponentTypeIdentifier.1:opt                                        -- _1,
   ComponentTypeIdentifier.1:opt.1:seq                                  -- _1 KW["::"],
   Prototypes                                                           -- _1,
   Prototypes.1:iter                                                    -- _1,
   Features                                                             -- _1,
   Features.1:iter                                                      -- _1,
   FlowSpecs                                                            -- _1,
   FlowSpecs.1:iter                                                     -- _1,
   ComponentTypePropertyAssociations                                    -- _1,
   ComponentTypePropertyAssociations.1:iter                             -- _1,
   ContainedPropertyAssociations                                        -- _1,
   ContainedPropertyAssociations.1:iter                                 -- _1,
   ComponentPrototypes                                                  -- KW["prototypes"] _1,
   ComponentFeatures                                                    -- KW["features"] _1,
   ComponentFlowSpecs                                                   -- KW["flows"] _1,
   ComponentPropertyAssociations                                        -- KW["properties"] _1,
   Component_Type                                                       -- _1 _2 _3 _4 _5 _6 _7 _8 KW["end"] _9 KW[";"],
   Component_Type.3:opt                                                 -- _1,
   Component_Type.4:opt                                                 -- _1,
   Component_Type.5:opt                                                 -- _1,
   Component_Type.6:opt                                                 -- _1,
   Component_Type.7:opt                                                 -- _1,
   Component_Type.8:iter-star                                           -- _1,
   Component_Type                                                       -- _1 _2 _3 _4 _5 _6 _7 _8 KW["end"] _9 KW[";"],
   Component_Type.3:opt                                                 -- _1,
   Component_Type.4:opt                                                 -- _1,
   Component_Type.5:opt                                                 -- _1,
   Component_Type.6:opt                                                 -- _1,
   Component_Type.7:opt                                                 -- _1,
   Component_Type.8:opt                                                 -- _1,
   Component_Type.8:opt.1:iter-star                                     -- _1,
   Package_spec                                                         -- KW["package"] _1 KW["public"] _2 _3 _4 KW["end"] _5 KW[";"],
   Package_spec.3:opt                                                   -- _1,
   Package_spec.3:opt.1:seq                                             -- KW["private"] _1,
   Package_spec.4:opt                                                   -- _1,
   Package_spec.4:opt.1:seq                                             -- KW["properties"] _1,
   Package_spec                                                         -- KW["package"] _1 KW["public"] _2 _3 _4 KW["end"] _5 KW[";"],
   Package_spec.3:opt                                                   -- _1,
   Package_spec.3:opt.1:seq                                             -- KW["private"] _1,
   Package_spec.4:opt                                                   -- _1,
   Package_spec.4:opt.1:seq                                             -- KW["properties"] _1,
   PropertyAssociations                                                 -- _1,
   PropertyAssociations.1:iter                                          -- _1,
   Pack_Declarations                                                    -- _1 _2,
   Pack_Declarations.1:iter-star                                        -- _1,
   Pack_Declarations.2:iter-star                                        -- _1,
   Pac_kageName                                                         -- _1 _2,
   Pac_kageName.1:iter-star-sep                                         -- _1 KW["::"],
   Import_Declaration                                                   -- KW["with"] _1 KW[";"],
   Import_Declaration.1:iter-sep                                        -- _1 KW[","],
   Import_Declaration                                                   -- KW["with"] _1 KW[","] _2 KW[";"],
   Import_Declaration.2:iter-star-sep                                   -- _1 KW[","],
   Import_Declaration                                                   -- KW["with"] _1 KW[","] _2 KW[";"],
   Import_Declaration.2:iter-star-sep                                   -- _1 KW[","],
   Import_Declaration                                                   -- KW["with"] _1 KW[";"],
   Import_Declaration.1:iter-sep                                        -- _1 KW[","],
   Alias_Declaration                                                    -- _1 KW["renames"] KW["package"] _2 KW[";"],
   Alias_Declaration                                                    -- _1 KW["renames"] _2 _3 KW[";"],
   Alias_Declaration.1:opt                                              -- _1,
   Alias_Declaration                                                    -- _1 KW["renames"] KW["feature"] KW["group"] _2 KW[";"],
   Alias_Declaration.1:opt                                              -- _1,
   Alias_Declaration                                                    -- KW["renames"] _1 KW["::"] KW["all"] KW[";"],
   Packagespec_AADLSpecification                                        -- _1,
   Packagespec_AADLSpecification.1:iter                                 -- _1,
   PropertySet_AADLSpecification                                        -- _1,
   PropertySet_AADLSpecification.1:iter                                 -- _1,
   Module                                                               -- KW["module"] _1 _2,
   Module.2:iter-star                                                   -- _1,
   AADLmodule                                                           -- _1
]